build-nextcloud-app.sh, proxy.php
Some cosmetic changes - split the reformatting and the actual code + some prevention of infinite looping...
=> This combines the Ash'es work and mine into one

proxy.php
To be used to detect problems with the setup.
=> Implement more thorough status checks, and potentially return status:error

proxy.php
The app seemed to have issues with Nextcloud running on a port that
was not 80/443.
=> Use HTTP_HOST instead of SERVER_NAME because it contains the port

proxy.php
On some setups (PHP 7.2 with nginx) apache_request_headers() is not available, so query.php is causing server errors. getallheaders is an alias to apache_request_headers, and going for the apache-free naming is more sensible imho, as it not only covers apache.
Beware, some headers might not get the proper casing. I have not seen issues on quick testing though. This is based on a prior comment to https://www.php.net/manual/en/function.getallheaders.php.
=> polyfill apache_request_headers for PHP <= 7.2

proxy.php
fontconfig is necessary for the AppImage to work, but many server
systems do not have it.
I've considered adding it to the AppImage, but then there are many
reports of AppImages not working due to containing fontconfig older than
the system one in case the newer fontconfig contains changes in the
configuration files (like new xml tags) that are not known for the older
one.
=> Check for fontconfig in proxy.php?status.

proxy.php
Most notably this removes the attempt to detect Docker / LXC, and instead just falls back to --appimage-extract-and-run when the run without that fails. That should cover even the cases when the FUSE is not installed on the system (that would otherwise run with that just fine).
=> Improvements in the AppImage startup

proxy.php
This is the ultimate check; but unfortunately we cannot be 100% sure it
is due to the glibc vs. musl, so report only the general error.
=> Better check for the fail on musl-based distros.

proxy.php
Let me summarize the problems:
* ldd - on some distros, it reported "not a dynamic executable" and
returned an error (even though the AppImage would work there)
* executing the AppImage with --appimage-version - from a reason that
escapes me this tries to fuse mount the AppImage; so on distros where
we fallback to --appimage-extract-and-run, this fails
So the hope is that that this will finally solve the problem - on the
"working" distros it seems to provide the info even on the distros where
ldd does not work; and on the non-working ones this returns a failure.
=> Another try for the right check how to detect musl-based distros.

proxy.php
fixes #2 
@juliushaertl stated in the issue:
> I'm not entirely sure how to solve this properly. In Nextcloud we use HTTP_X_FORWARDED_PROTO and HTTP_X_FORWARDED_FOR but we also have dedicated config.php flags to override the protocol/host, but that would require you to somehow setup the server classes to access the config values, so that would have a performance impact again.
Now, I understand richdocumentscode is agnostic to whatever service runs on top, Nextcloud or not. So adding Nextcloud logic is not needed or reasonable, but expending it is. 
What is not included is also whether the forwarding proxy is trusted, or not. Upgrading to HTTPS should not do any harm, though, and downgrading is prevented, as it does not overrule the HTTPS env.
P.S.: for completeness, it only has effect …
=> detect HTTPS from proxies

appinfo/info.xml
@timar Not sure how you build the arm app but that should then just replace the architecture entry with aarch64
This will make sure that the app cannot be installed by accident on the wrong architecture and the user will be seeing a warning in the Nextcloud app management about it with Nextcloud 20+ (https://github.com/nextcloud/server/pull/22844)
=> Add architecture dependency

proxy.php
This patch prevents from showing an error if
permissions are good enough to run AppImage
(if permissions are 0744 or higher) but chmod fails.
Signed-off-by: Szymon Kłos <szymon.klos@collabora.com>
=> Check permissions before chmod

build-nextcloud-app.sh, proxy.php
Build script runs AppImage and saves capabilities endpoint
output to file.
When AppImage is not started yet - cached file content will be sent.
Otherwise proxy will redirrect to the acctual endpoint.
=> If appimage is starting send cached capabilities

proxy.php
I propose to remove reference to /proc directory.
/proc make mandatory to openbasedir /proc, what is quite dangerous.
Refer to https://stackoverflow.com/questions/9874331/how-to-check-whether-specified-pid-is-currently-running-without-invoking-ps-from
and php -d memory_limit=512M occ app:install richdocumentscode creating openbase_dir error #107
=> Security issue : modification proposed to avoid /proc in openbasedir

proxy.php
This should make sure that we return a proper error instead of throwing a fatal one to the nextcloud log
Closes https://github.com/nextcloud/richdocuments/issues/2345
=> Check if exec is available before calling

README.md
- Add disk space required when FUSE isn't available since it's significant
- Adapt updated name for Nextcloud Office integration app (https://github.com/nextcloud/richdocuments/pull/1921)
- Reword glibc requirement slightly for clarity
- Extend paragraph for `--appimage-extract-and-run` fallback behavior by clarifying the warnings related to FUSE are expected in that scenario
=> docs(README): Update disk space reqs + minor misc

appinfo/info.xml
To avoid confusion since the `richdocuments` (NC integration app) is labeled today "Nextcloud Office".
Fixes: https://github.com/nextcloud/richdocuments/issues/2083
=> fix(appstore) Fix NC Office integration app link name

templates/admin.php
Minor tweaks to bring labels/references up-to-date in the Admin settings page.
* Update "where to go" to match NC's current settings menu structure
* Update "`richdocuments` needs to be installed" copy to match current name used in AppStore & docs
=> fix(admin): Update copy in admin settings for accuracy

README.md
After struggling a little on install on my arm64 system, I propose some small changes in the doc to make it clearer how to install on such systems.
Also see https://github.com/CollaboraOnline/richdocumentscode/issues/283
=> docs(README): Clarify installation for ARM64

proxy.php
Check the actual length of the coolwsd hash, it is 10 characters by now.
This fixes the issues https://github.com/CollaboraOnline/richdocumentscode/issues/295 and https://github.com/CollaboraOnline/richdocumentscode/issues/298
=> fix length mismatch on coolwsd hash

proxy.php
Calling http_response_code() after print() has no effect and it logs a warning "headers already sent" on the web server logs. When PHP has display_errors enabled, the warning is also sent as a response to the browser, and the browser is unable to open CODE application.
This commit fixes #286 and #270 by moving one http_response_code(400) call before "print", and by removing two useless http_response_code(200);, which is the default value.
=> Move calls to http_response_code() before doing print()
